### ISSUE TITLE
Getting Error with ETH Address

### ISSUE THREAD

**Issue by dharmendrakariya** [sky-ecosystem/dockerized-auction-keeper#47]
I am running ```flip-eth-a``` with below envs and keypair

```
FLIP_ETH_A_ACCOUNT_ADDRESS='0x91403e02d0d6442e11ba67BcB38Cad421Eb31EdB'
FLIP_ETH_A_ACCOUNT_KEY='key_file=/opt/keeper/secrets/keystore-flip-eth-a.json,pass_file=/opt/keeper/secrets/password-flip-eth-a.txt'
#FLIP_ETH_A_ACCOUNT_KEY='key_file=/opt/keeper/secrets/keystore-flip-eth-a.json,pass_file=/opt/keeper/secrets/password-flip-eth-a.txt'
FLIP_ETH_A_DAI_IN_VAT=${DAI_IN_VAT}
FLIP_ILK_ETH_A=ETH-A
FLIP_MINIMUM_ETH_A_AUCTION_ID_TO_CHECK=0
FLIP_ETH_URL="https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd"
FLIP_ETH_A_DISCOUNT=0.25 # e.g. 0.25 = 25% discount from FMV

```
Below is my keypair

```
Private key: 0x0649d94a8af180f1d8674a*f12*96a87*0afe581af623810785d3374
Public address: 0x91403e02d0d6442e11ba67BcB38Cad421Eb31EdB
```
I am confused with the ```FLIP_ETH_A_ACCOUNT_ADDRESS``` ENV ! do i have to use another wallet ? or the same public key has to be given to that ENV! (like the way I did!

also with this settings I am getting below error

```
Starting flip-eth-a ... done
Attaching to flip-eth-a
flip-eth-a                | Traceback (most recent call last):
flip-eth-a                |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
flip-eth-a                |     "__main__", mod_spec)
flip-eth-a                |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
flip-eth-a                |     exec(code, run_globals)
flip-eth-a                |   File "/opt/keeper/auction-keeper/auction_keeper/main.py", line 951, in <module>
flip-eth-a                |     AuctionKeeper(sys.argv[1:]).main()
flip-eth-a                |   File "/opt/keeper/auction-keeper/auction_keeper/main.py", line 164, in __init__
flip-eth-a                |     self.mcd = DssDeployment.from_node(web3=self.web3)
flip-eth-a                |   File "/opt/keeper/auction-keeper/lib/pymaker/pymaker/deployment.py", line 365, in from_node
flip-eth-a                |     return DssDeployment.from_network(web3=web3, network=network)
flip-eth-a                |   File "/opt/keeper/auction-keeper/lib/pymaker/pymaker/deployment.py", line 375, in from_network
flip-eth-a                |     return DssDeployment.from_json(web3=web3, conf=open(addresses_path, "r").read())
flip-eth-a                |   File "/opt/keeper/auction-keeper/lib/pymaker/pymaker/deployment.py", line 354, in from_json
flip-eth-a                |     return DssDeployment(web3, DssDeployment.Config.from_json(web3, conf))
flip-eth-a                |   File "/opt/keeper/auction-keeper/lib/pymaker/pymaker/deployment.py", line 202, in from_json
flip-eth-a                |     pause = DSPause(web3, Address(conf['MCD_PAUSE']))
flip-eth-a                |   File "/opt/keeper/auction-keeper/lib/pymaker/pymaker/governance.py", line 66, in __init__
flip-eth-a                |     self._contract = self._get_contract(web3, self.abi, address)
flip-eth-a                |   File "/opt/keeper/auction-keeper/lib/pymaker/pymaker/__init__.py", line 206, in _get_contract
flip-eth-a                |     raise Exception(f"No contract found at {address}")
flip-eth-a                | Exception: No contract found at 0xbE286431454714F511008713973d3B053A2d38f3
flip-eth-a exited with code 1
```

**Comment by nikozalo** [comment]
This repo is deprecated. I suggest you take a look at:
- https://github.com/sidestream-tech/unified-auctions-ui/tree/main/bot
or
- https://github.com/makerdao/auction-demo-keeper
To run a keeper.

**Comment by dharmendrakariya** [comment]
@lollike  https://github.com/makerdao/auction-keeper is this deprecated as well? Coz when I followed this doc https://docs.makerdao.com/keepers/auction-keepers/auction-keeper-bot-setup-guide I get the same error!

**Comment by dharmendrakariya** [comment]
![image](https://user-images.githubusercontent.com/22043860/173841139-15720f58-d38d-40cc-9700-9c565200bfe6.png)
